# -*- mode: ruby -*-
# vim: set ft=ruby :
#Path to HDD on host

Vagrant.configure(2) do |config|
  config.vm.box = "debian/bullseye64"
  config.vm.box_version = "11.20230615.1" 
  config.vm.define "server" do |ser|
    ser.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    ser.vm.hostname = "server"
    ser.vm.network "private_network", ip: "192.168.56.10"
 end

  config.vm.define "client" do |cl|
    cl.vm.provider "virtualbox" do |v|
      v.memory = 512
      v.cpus = 1
    end
    cl.vm.hostname = "client"
    cl.vm.network "private_network", ip: "192.168.56.20"
    cl.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/play.yml"
      ansible.inventory_path = "ansible/hosts"
      ansible.host_key_checking = "false"
     # ansible.verbose = "vvv"
      ansible.limit = "all"
    end
  end
end
